// EcoRisk AI multi-site dashboard. All values come from window.MODEL_DATA (generated by
// build_data.py from ml/model_results.json, itself generated by ml/train_model.py). No
// number on this page is hand-entered -- see sihPlan/memory.md for the full fact ledger.
(function () {
  const D = window.MODEL_DATA;

  const FEATURE_LABELS = {
    ndvi_trend_slope: "NDVI trend (vegetation)",
    ndbi_trend_slope: "NDBI trend (built-up)",
    mean_slope_degrees: "Mean slope",
    elevation_mean_m: "Elevation",
    rainfall_anomaly_pct: "Rainfall anomaly",
    terrain_hill: "Terrain = hill",
  };

  // ---------- 2. Evidence ----------
  const realSites = D.risk_ranking;
  const nHill = realSites.filter((s) => s.terrain_type === "hill").length;
  const nCoastal = realSites.filter((s) => s.terrain_type === "coastal").length;
  document.getElementById("ev-n-real").textContent = D.n_sites_real;
  document.getElementById("ev-n-hill").textContent = nHill;
  document.getElementById("ev-n-coastal").textContent = nCoastal;
  document.getElementById("ev-n-pending").textContent = D.n_sites_pending;

  const grid = document.getElementById("site-grid");
  realSites.forEach((s) => {
    const chip = document.createElement("div");
    chip.className = "site-chip " + (s.disaster_occurred ? "disaster" : "control");
    chip.innerHTML = `<div class="name-row"><span class="name"><span class="dot"></span>${s.site_name}</span><span class="risk-val">${(s.predicted_risk_prob * 100).toFixed(0)}%</span></div>
      <div class="terrain">${s.terrain_type}${s.disaster_occurred ? " · disaster" : " · control"}</div>`;
    grid.appendChild(chip);
  });
  D.pending_sites.forEach((s) => {
    const chip = document.createElement("div");
    chip.className = "site-chip pending";
    chip.innerHTML = `<div class="name">${s.site_id}</div><div class="terrain">${s.terrain_type} · not pulled</div>`;
    grid.appendChild(chip);
  });

  // ---------- 3. Feature importance ----------
  const fiEntries = Object.entries(D.feature_importance).sort((a, b) => Math.abs(b[1]) - Math.abs(a[1]));
  const maxAbs = Math.max(...fiEntries.map(([, v]) => Math.abs(v)));
  const fiChart = document.getElementById("fi-chart");
  fiEntries.forEach(([key, val]) => {
    const row = document.createElement("div");
    row.className = "fi-row";
    const pct = (Math.abs(val) / maxAbs) * 48; // half-track max, since bar can go either direction from center
    const leftPos = val < 0 ? 50 - pct : 50;
    row.innerHTML = `
      <div class="fi-label">${FEATURE_LABELS[key] || key}</div>
      <div class="fi-track">
        <div class="fi-zero" style="left:50%"></div>
        <div class="fi-bar" style="left:${leftPos}%; width:${pct}%"></div>
      </div>
      <div class="fi-val">${val > 0 ? "+" : ""}${val.toFixed(2)}</div>
    `;
    fiChart.appendChild(row);
  });
  const topFeature = fiEntries[0];
  const topLabel = FEATURE_LABELS[topFeature[0]] || topFeature[0];
  const direction = topFeature[1] < 0 ? "declining" : "rising";
  document.getElementById("fi-callout").textContent =
    `Strongest predictor: ${topLabel} (coefficient ${topFeature[1].toFixed(3)}). ` +
    `A ${direction} trend in this signal is most strongly associated with disaster occurrence across the ${D.n_sites_real} real sites -- ` +
    `this is what the model found on its own, not what we told it to look for.`;

  // ---------- 4. Stress test ----------
  const loocvPct = D.loocv.accuracy * 100;
  document.getElementById("loocv-frac").textContent = `${D.loocv.correct}/${D.loocv.total} (${loocvPct.toFixed(0)}%)`;
  document.getElementById("loocv-bar").style.width = loocvPct.toFixed(0) + "%";
  document.getElementById("loocv-note").textContent =
    `Trained and tested on every real site, one held out at a time -- the standard approach for a dataset this small.`;

  const ctList = document.getElementById("ct-list");
  if (D.cross_terrain) {
    const ct = D.cross_terrain;
    ct.site_ids.forEach((siteId, i) => {
      const site = realSites.find((s) => s.site_id === siteId);
      const hit = ct.predicted[i] === ct.actual[i];
      const li = document.createElement("li");
      li.innerHTML = `<span>${site ? site.site_name : siteId}</span>
        <span class="ct-badge ${hit ? "hit" : "miss"}">${hit ? "correct" : "missed"} (predicted ${ct.predicted[i] ? "risk" : "safe"}, actual ${ct.actual[i] ? "disaster" : "control"})</span>`;
      ctList.appendChild(li);
    });
    const summary = document.createElement("li");
    summary.style.marginTop = "6px";
    summary.style.borderBottom = "none";
    summary.innerHTML = `<strong>${ct.n_correct} of ${ct.site_ids.length} correct</strong> -- trained only on ${ct.n_hill_train} hill sites, never saw a coastal site during training.`;
    ctList.appendChild(summary);
  } else {
    ctList.innerHTML = "<li>Not enough sites per terrain type yet to run this check.</li>";
  }

  // ---------- Appendix: risk table ----------
  const tbody = document.getElementById("risk-table-body");
  let sortKey = "predicted_risk_prob";
  let sortDir = -1;

  function renderTable() {
    const rows = [...realSites].sort((a, b) => {
      const av = a[sortKey], bv = b[sortKey];
      if (typeof av === "string") return sortDir * av.localeCompare(bv);
      return sortDir * (av - bv);
    });
    tbody.innerHTML = "";
    rows.forEach((s) => {
      const tr = document.createElement("tr");
      tr.className = s.disaster_occurred ? "disaster" : "control";
      tr.innerHTML = `
        <td>${s.site_name}</td>
        <td>${s.terrain_type}</td>
        <td>${s.disaster_occurred ? (s.disaster_type || "disaster") : "control"}</td>
        <td class="num">${(s.predicted_risk_prob * 100).toFixed(1)}%</td>
        <td class="num">${s.ndvi_trend_slope >= 0 ? "+" : ""}${s.ndvi_trend_slope.toFixed(4)}</td>
        <td class="num">${s.rainfall_anomaly_pct >= 0 ? "+" : ""}${s.rainfall_anomaly_pct.toFixed(1)}%</td>
      `;
      tbody.appendChild(tr);
    });
  }
  document.querySelectorAll("#risk-table th[data-key]").forEach((th) => {
    th.addEventListener("click", () => {
      const key = th.getAttribute("data-key");
      sortDir = key === sortKey ? -sortDir : -1;
      sortKey = key;
      renderTable();
    });
  });
  renderTable();

  // ---------- Appendix: live rainfall (top-ranked real site) ----------
  const topSite = [...realSites].sort((a, b) => b.predicted_risk_prob - a.predicted_risk_prob)[0];
  const statusEl = document.getElementById("live-status");
  document.getElementById("live-sub").textContent =
    `One genuine live pull (Open-Meteo, no key required) for ${topSite.site_name}, the model's current top-ranked site, proves this isn't fully static.`;
  if (topSite.latitude != null && topSite.longitude != null) {
    fetch(`https://api.open-meteo.com/v1/forecast?latitude=${topSite.latitude}&longitude=${topSite.longitude}&current=precipitation,temperature_2m&daily=precipitation_sum&timezone=auto`)
      .then((r) => {
        if (!r.ok) throw new Error("HTTP " + r.status);
        return r.json();
      })
      .then((json) => {
        document.getElementById("live-precip").textContent = json.current.precipitation.toFixed(1);
        document.getElementById("live-temp").textContent = json.current.temperature_2m.toFixed(1);
        document.getElementById("live-today").textContent = json.daily.precipitation_sum[0].toFixed(1);
        statusEl.textContent = "Live — fetched " + new Date(json.current.time).toLocaleString();
        statusEl.className = "live-status ok";
      })
      .catch((err) => {
        statusEl.textContent = "Live fetch failed (" + err.message + ") — network may be unavailable in this environment.";
        statusEl.className = "live-status error";
      });
  } else {
    statusEl.textContent = "No coordinates available for the top-ranked site.";
    statusEl.className = "live-status error";
  }
})();
