#!/usr/bin/env python3
"""Embeds ml/model_results.json into dashboard/data.js as window.MODEL_DATA. A plain
<script src> avoids a fetch() dependency for local data when this page is opened via
file:// (only the live-rainfall call in app.js needs real network access). Re-run this
after any ml/train_model.py rerun so the dashboard never drifts from the model's actual
output."""
import json
import os

BASE = os.path.dirname(os.path.abspath(__file__))
SRC = os.path.join(BASE, "..", "ml", "model_results.json")
OUT = os.path.join(BASE, "data.js")

with open(SRC) as f:
    data = json.load(f)

with open(OUT, "w") as f:
    f.write("// Generated by dashboard/build_data.py from ml/model_results.json -- do not hand-edit.\n")
    f.write("window.MODEL_DATA = ")
    json.dump(data, f, indent=2)
    f.write(";\n")

print(f"Wrote {OUT} ({data['n_sites_real']} real sites, LOOCV {data['loocv']['accuracy']})")
