#!/usr/bin/env python3
"""Converts real CSVs in datasourceSIH/ into demo/data.js (embedded JSON).
No values are invented here -- every number is read straight from the source CSVs.
Re-run this whenever the source CSVs change."""
import csv
import json
import os

BASE = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SRC = os.path.join(BASE, "datasourceSIH")
OUT = os.path.join(BASE, "demo", "data.js")


def read_merged_timeline():
    path = os.path.join(SRC, "joshimath_merged_timeline.csv")
    rows = []
    with open(path, newline="") as f:
        for r in csv.DictReader(f):
            rows.append({
                "date": r["date"],
                "ndvi": float(r["ndvi_avg"]),
                "ndbi": float(r["ndbi_avg"]),
                "rainfall_mm": float(r["rainfall_mm"]),
                "event_marker": r["event_marker"] or None,
            })
    return rows


def read_power_rainfall():
    path = os.path.join(SRC, "POWER_Point_Daily_20190101_20230521_030d56N_079d56E_LST.csv")
    rows = []
    with open(path, newline="") as f:
        lines = f.readlines()
    header_idx = next(i for i, l in enumerate(lines) if l.startswith("YEAR,DOY"))
    reader = csv.DictReader(lines[header_idx:])
    for r in reader:
        year = int(r["YEAR"])
        doy = int(r["DOY"])
        from datetime import date, timedelta
        d = date(year, 1, 1) + timedelta(days=doy - 1)
        val = float(r["PRECTOTCORR"])
        rows.append({"date": d.isoformat(), "rainfall_mm": val})
    return rows


def read_dem_slope():
    path = os.path.join(SRC, "joshimath_dem_slope.csv")
    with open(path, newline="") as f:
        r = next(csv.DictReader(f))
    return {
        "elevation_max_m": float(r["elev_elevation_max"]),
        "elevation_mean_m": float(r["elev_elevation_mean"]),
        "elevation_min_m": float(r["elev_elevation_min"]),
        "slope_max_deg": float(r["slope_slope_max"]),
        "slope_mean_deg": float(r["slope_slope_mean"]),
        "slope_min_deg": float(r["slope_slope_min"]),
    }


def read_events():
    path = os.path.join(SRC, "joshimath_disaster_event_log.csv")
    events = []
    with open(path, newline="") as f:
        for r in csv.DictReader(f):
            if not r["event_date"]:
                continue
            events.append({
                "event_date": r["event_date"],
                "location": r["location"],
                "hazard_type": r["hazard_type"],
                "subsidence_cm": float(r["subsidence_cm"]) if r["subsidence_cm"] else None,
                "period_description": r["period_description"],
                "description": r["description"],
                "source": r["source"],
            })
    return events


def main():
    data = {
        "coordinates": {"lat": 30.5551, "lon": 79.5641},
        "merged_timeline": read_merged_timeline(),
        "power_rainfall_daily": read_power_rainfall(),
        "dem_slope": read_dem_slope(),
        "events": read_events(),
        "threshold": {
            "region": "Chamoli-Joshimath, Garhwal Himalaya",
            "antecedent_10day_mm": 55,
            "antecedent_20day_mm": 185,
            "source": "Kanungo & Sharma (2014), Landslides 11, 629-638, DOI 10.1007/s10346-013-0438-9",
            "caveat": "Primary paper paywalled; figures taken from a secondary source summarizing it.",
        },
    }
    with open(OUT, "w") as f:
        f.write("// AUTO-GENERATED by demo/build_data.py from datasourceSIH/*.csv -- do not hand-edit.\n")
        f.write("window.JOSHIMATH_DATA = ")
        json.dump(data, f)
        f.write(";\n")
    print(f"Wrote {OUT}")
    print(f"  merged_timeline rows: {len(data['merged_timeline'])}")
    print(f"  power_rainfall_daily rows: {len(data['power_rainfall_daily'])}")
    print(f"  events: {len(data['events'])}")


if __name__ == "__main__":
    main()
